FROM openjdk
RUN mkdir "/app"
WORKDIR /app
COPY server.jar /app/server.jar
CMD java -jar /app/server.jar Legacy 127.0.0.1 1234 9144 8080 12530
CMD java -jar /app/server.jar Default 127.0.0.1 1234 9144 80 443
